### ISSUE TITLE
[BUG] The Error Code "TokenInvalid" did not show the error message correctly

### ISSUE THREAD

**Issue by NotKeyYT** [ItzKeyYT/BadgeGiver#1]
**Describe the bug**
The error code is "TokenInvalid" and the code did not identify. Instead, it thought that is a different error code other than "TokenInvalid" and shows the error message that is other than the it's own "TokenInvalid" error message.

**To Reproduce**
1. Run the code with "node ." or "npm run bot"
2. Don't use a real bot token (Type a random letter or number.)

**Expected behavior**
It should say "☒ | An error occurred: The discord bot token you've provided is not valid." '🔃 | Please try to run the code again and enter a valid token. Usage: "node ." or "npm run bot"'

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 1.2.2

**Comment by ykitzkey** [comment]
New update v1.2.3 should patch this bug and this bug issue will close.
